COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: insecure

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:199786@localhost:3306/testdb?charset=utf8'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置

  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml

  # redis配置
#  REDIS_EXPIRE: 60*60
#  REDIS_HOST: 127.0.0.1
#  REDIS_PORT: 6379
#  REDIS_DB: 1

  # 是否开启定时任务,默认不开启
  SCHEDULER_OPEN: True

  # 定时任务配置
  SCHEDULER_API_ENABLED: True
  JOBS:
    - id: my_job
      func: task.task:my_job
      trigger: interval
      seconds: 10
      #hour: 12
      #minute: 1
#    - id: db_query
#      func: task.task:db_query
#      trigger: interval
#      minutes: 1
    - id: db_insert
      func: task.task:db_insert
      trigger: interval
      minutes: 2

    - id: yuanyou_insert
      func: task.task:yuanyou_insert
      trigger: interval
      minutes: 2


DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True
  REDIS_PORT: 6380

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:199786@flask-mysql:3306/testdb?charset=utf8'